export const fileTypes = {
	".ico": "image/vnd.microsoft.icon",
	//audio
	".aac": "audio/aac",
	".avi": "video/x-msvideo",
	".bin": "application/octet-stream",
	".mp3": "audio/mpeg",
	".oga": "audio/ogg",
	//text
	".html": "text/html",
	".htm": "text/html",
	".shtml": "text/html",
	".htmlx": "text/html",
	".hbs": "text/html",
	".txt": "text/plain",
	".js": "text/javascript",
	".mjs": "text/javascript",
	".ts": "text/javascript",
	".css": "text/css",
	".json": "application/json",
	".csv": "text/csv",
	".md": "text/markdown",
	//xml
	".xhtml": "application/xhtml+xml",
	".xml": "application/xml",
	//document
	".doc": "application/msword",
	".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	".epub": "application/epub+zip",
	".pdf": "application/pdf",
	".php": "application/x-httpd-php",
	".ppt": "application/vnd.ms-powerpoint",
	".sh": "application/x-sh",
	".xls": "application/vnd.ms-excel",
	".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	".csh": "application/x-csh",
	//archive
	".gz": "application/gzip",
	".zip": "application/zip",
	".rar": "application/vnd.rar",
	".7z": "application/x-7z-compressed",
	".tar": "application/x-tar",
	".jar": "application/java-archive",
	".bz": "application/x-bzip",
	".bz2": "application/x-bzip2",
	//font
	".ttf": "font/ttf",
	".woff": "font/woff",
	".woff2": "font/woff2",
	".otf": "font/otf",
	".eot": "application/vnd.ms-fontobject",
	//image
	".bmp": "image/bmp",
	".png": "image/png",
	".jpg": "image/jpg",
	".jpeg": "image/jpeg",
	".webp": "image/webp",
	".avif": "image/avif",
	".svg": "image/svg+xml",
	".heic": "mage/heic",
	".gif": "image/gif",
	//video
	".mp4": "video/mp4",
	".mpeg": "video/mpeg",
	".ogv": "video/ogg",
	".3gp": "video/3gpp",
};
